// <auto-generated />
using System;
using Ferrecode.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ferrecode.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240313204256_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ferrecode.Domain.Inventarios.Inventario", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IDProductos")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDPuntoDeVenta")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("IDProductos");

                    b.HasIndex("IDPuntoDeVenta");

                    b.ToTable("Inventarios", (string)null);
                });

            modelBuilder.Entity("Ferrecode.Domain.Productos.Producto", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Peso")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VolumenEmpaque")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.ToTable("Productos", (string)null);
                });

            modelBuilder.Entity("Ferrecode.Domain.PuntosDeVenta.PuntoDeVenta", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("PuntosDeVenta", (string)null);
                });

            modelBuilder.Entity("Ferrecode.Domain.Inventarios.Inventario", b =>
                {
                    b.HasOne("Ferrecode.Domain.Productos.Producto", null)
                        .WithMany()
                        .HasForeignKey("IDProductos")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ferrecode.Domain.PuntosDeVenta.PuntoDeVenta", null)
                        .WithMany()
                        .HasForeignKey("IDPuntoDeVenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ferrecode.Domain.Productos.Producto", b =>
                {
                    b.OwnsOne("Ferrecode.Domain.Productos.Medida", "Medida", b1 =>
                        {
                            b1.Property<Guid>("ProductoID")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("UnidadDeMedida")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("UnidadDeMedida");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("ValorMedida");

                            b1.HasKey("ProductoID");

                            b1.ToTable("Productos");

                            b1.WithOwner()
                                .HasForeignKey("ProductoID");
                        });

                    b.Navigation("Medida");
                });
#pragma warning restore 612, 618
        }
    }
}
